language: python
python:
  - "3.5.3"
  
addons:
  apt:
    packages:
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev
# command to install dependencies
install: 
  - sudo apt-get update
  - pip install requests coveralls nose-htmloutput nose coverage openpyxl metaphone pyexcel pyexcel-xls pyexcel-xlsx textdistance
  - pip install gedcompy mapbox langdetect geotext docutils fuzzywuzzy
services:
  - xvfb
script: nosetests -v --with-id  --with-coverage --cover-package=./

after_success:  
  - coveralls 